---
- name: Generiere /etc/ssh/sshd_config
  template:
    src: "sshd_config.jumphost.j2"
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: '0644'
  become: yes
  when:
    - secure_ssh_config